title: Odin Strabo Jensen
description: My personal site with Minimal Mistakes
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "mint"

plugins:
  - jekyll-include-cache
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"
markdown: kramdown
