title: My Blog
description: A better blog using Minimal Mistakes
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "mint" # options: default, dark, air, mint, neon, etc.

plugins:
  - jekyll-include-cache
  - jekyll-paginate
markdown: kramdown
paginate: 5
paginate_path: /page:num/