title: Odin Strabo Jensen
description: My personal site powered by Minimal Mistakes
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

author: default

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  
fontawesome: true

paginate: 5
paginate_path: "/page:num/"
markdown: kramdown

navigation:
  main: main

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-XBDR3W7R47"
